export const structureClient = [
  {
    name: "firstName",
    type: "text",
    label: "firstName",
    required: true,
    block: false,
  },
  {
    name: "middleName",
    type: "text",
    label: "middleName",
    required: false,
    block: false,
  },
  {
    name: "lastName",
    type: "text",
    label: "lastName",
    required: true,
    block: false,
  },
  {
    name: "phone",
    type: "tel",
    label: "phone",
    required: true,
    block: false,
  },
  {
    name: "email",
    type: "email",
    label: "email",
    required: true,
    block: false,
  },
  {
    name: "password",
    type: "password",
    label: "password",
    required: true,
    block: false,
    initialOnly: true,
  },
  {
    name: "imgUrl",
    type: "text",
    label: "imgUrl",
    required: false,
    block: true,
  },
  {
    name: "imgAlt",
    type: "text",
    label: "imgAlt",
    required: false,
    block: false,
  },
  {
    name: "state",
    type: "text",
    label: "state",
    required: false,
    block: false,
  },
  {
    name: "country",
    type: "text",
    label: "country",
    required: true,
    block: false,
  },
  { name: "city", type: "text", label: "city", required: true, block: false },
  {
    name: "street",
    type: "text",
    label: "street",
    required: true,
    block: false,
  },
  {
    name: "houseNumber",
    type: "number",
    label: "houseNumber",
    required: true,
    block: false,
  },
  {
    name: "zip",
    type: "number",
    label: "zip",
    required: false,
    block: false,
  },
  {
    name: "business",
    type: "boolean",
    label: "business",
    required: false,
    block: false,
  },
];
