export const structureCard = [
  {
    name: "title",
    type: "text",
    label: "title",
    required: true,
    block: false,
  },
  {
    name: "subtitle",
    type: "text",
    label: "subtitle",
    required: true,
    block: false,
  },
  {
    name: "description",
    type: "text",
    label: "description",
    required: true,
    block: false,
  },
  {
    name: "phone",
    type: "tel",
    label: "phone",
    required: true,
    block: false,
  },
  {
    name: "email",
    type: "email",
    label: "email",
    required: true,
    block: false,
  },
  {
    name: "web",
    type: "text",
    label: "web",
    required: true,
    block: false,
  },
  {
    name: "imgUrl",
    type: "text",
    label: "imgUrl",
    required: true,
    block: true,
  },
  {
    name: "imgAlt",
    type: "text",
    label: "imgAlt",
    required: true,
    block: false,
  },
  {
    name: "state",
    type: "text",
    label: "state",
    required: true,
    block: false,
  },
  {
    name: "country",
    type: "text",
    label: "country",
    required: true,
    block: false,
  },
  { name: "city", type: "text", label: "city", required: true, block: false },
  {
    name: "street",
    type: "text",
    label: "street",
    required: true,
    block: false,
  },
  {
    name: "houseNumber",
    type: "number",
    label: "houseNumber",
    required: true,
    block: false,
  },
  {
    name: "zip",
    type: "number",
    label: "postal code",
    required: true,
    block: false,
  },
];
